export const LOADER_TRUE = 'LOADER_TRUE';
export const LOADER_FALSE = 'LOADER_FALSE';
export const LOADING_PROGRESS = 'LOADING_PROGRESS';
export const LOADING_PROGRESS_COMPLETE = 'LOADING_PROGRESS_COMPLETE';

export const SIGNIN = 'SIGNIN';
export const LOGOUT = 'LOGOUT';

export const UPDATE_TOKENS = "UPDATE_TOKENS";

export const PRODUCT_LISTING = 'PRODUCT_LISTING';


export const SHOW_SUCCESS_ALERT = 'SHOW_SUCCESS_ALERT';
export const SHOW_ERROR_ALERT = 'SHOW_ERROR_ALERT';
export const SHOW_WARNING_ALERT = 'SHOW_WARNING_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';
